[FIX] use LABjs to load scripts to avoid recurring 'TypeError: Result of expression 'openerp._openerp[mod]' [undefined] is not a function.'
Might not be the best loader, not sure, but we only use it in two places so it's trivial to replace. It's also one of the oldest loaders so it should be pretty stable.

bzr revid: xmo@openerp.com-20110324203538-bk59e8wbiux47e7j