Bugfix:   AttributeError: 'list' object has no attribute 'get'   context was a list instead of a dict   resolution: use 'read' method instead of 'browse'
bzr revid: olt@tinyerp.com-20081009080041-ddju2msf57t2xy5m